### ISSUE TITLE
Add ability to specify specific buildspecs via crashloader.py

### ISSUE THREAD

**Issue by m8ttyB** [kimberlythegeek/tantalus#10]
We need the ability to run tests against specific build env configurations, including tracking which configurations failures are occurring on. The following is by no means a complete scoping of the work, we'll dig further into this feature while working on it.

- [ ] ~~On the individual workers, create the following directories on each worker in the builds directory. Nightly-{norton,kaspersky,mcafee,pandas, xyz}~~
- [ ] ~~Update the Workers table with following buildspecs {opt,debug}-{norton,kaspersky,mcafee,pandas,xyz}~~
- [x] Update crashworker.bat for buildspec so we can target specific build configurations
- [x] update crashloader.py

**Comment by bclary** [comment]
> We need the ability to run tests against specific build env configurations, including tracking which configurations failures are occurring on. The following is by no means a complete scoping of the work, we'll dig further into this feature while working on it.
> 
>     * [ ]  On the individual workers, create the following directories on each worker in the builds directory. Nightly-{norton,kaspersky,mcafee,pandas, xyz}

I know this is windows but you should eliminate the possibility and use nightly-...
> 
>     * [ ]  Update the Workers table with following buildspecs {opt,debug}-{norton,kaspersky,mcafee,pandas,xyz}

I think this will work. Do these need installation or setup after the build is downloaded and unzipped?

> 
>     * [ ]  Update crashworker.bat for buildspec so we can target specific build configurations

crashworker.sh needs to be updated. crashworker.bat just invokes crashworker.sh
> 
>     * [ ]  update crashloader.py

I don't think this will be necessary if the tables in the database have the approrpirate build specs defined.

**Comment by bclary** [comment]
One other question: Will each machine have all of the different products installed at once? Or will they only be installed on specific machines? I presume only one per machine?

**Comment by m8ttyB** [comment]
@bclary, you are correct in your assumption, each machine is planned to have only one 3rd party application installed. I'll leave the remain conversation for @kimberlythegeek to fill in the details.

**Comment by kimberlythegeek** [comment]
creating the directories was not a required step. Added buildspecs for bitdefender pro, kaspersky pro, and norton pro in the Branch table, and updated `crashworker.sh` on each worker to reflect the changes. documented the process in the readme
